//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int IDProd { get; set; }
        public string Articul { get; set; }
        public string ProdName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> MaxDiscount { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public Nullable<int> Suppiler { get; set; }
        public Nullable<int> ProdType { get; set; }
        public Nullable<double> CurrentDiscount { get; set; }
        public Nullable<int> Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Manufactures Manufactures { get; set; }
        public virtual ProdType ProdType1 { get; set; }
        public virtual Suppilers Suppilers { get; set; }
    }
}
